/*
 * This file was automatically generated by EvoSuite
 * Mon Sep 26 20:07:55 GMT 2022
 */

package example.Util;

import org.junit.Test;
import static org.junit.Assert.*;
import example.Util.ConversorMoedas;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

// @RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class ConversorMoedas_ESTest extends ConversorMoedas_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      ConversorMoedas conversorMoedas0 = new ConversorMoedas(0.0, 0.0);
      conversorMoedas0.setLibra(1.0);
      double double0 = conversorMoedas0.converteParaLibra(723.6810719723301);
      assertEquals(1.0, conversorMoedas0.libra, 0.01);
      assertEquals(723.6810719723301, double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      ConversorMoedas conversorMoedas0 = new ConversorMoedas((-2189.3124944925), (-2189.3124944925), 723.903436224, 723.903436224);
      conversorMoedas0.dolar = 723.903436224;
      double double0 = conversorMoedas0.somaValoresConverteDolar((-1492.0), 723.903436224);
      assertEquals((-768.096563776), conversorMoedas0.quantia, 0.01);
      assertEquals((-556027.7418692932), double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      ConversorMoedas conversorMoedas0 = new ConversorMoedas((-2189.3124944925), (-2189.3124944925), 723.903436224, 723.903436224);
      conversorMoedas0.somaValoresConverteDolar(-0.0, -0.0);
      double double0 = conversorMoedas0.getQuantia();
      assertEquals(-0.0, conversorMoedas0.quantia, 0.01);
      assertEquals(-0.0, double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      ConversorMoedas conversorMoedas0 = new ConversorMoedas(1.0, 1546.607325);
      conversorMoedas0.setQuantia((-1985.8473398087833));
      double double0 = conversorMoedas0.getQuantia();
      assertEquals((-1985.8473398087833), conversorMoedas0.quantia, 0.01);
      assertEquals((-1985.8473398087833), double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      ConversorMoedas conversorMoedas0 = new ConversorMoedas((-1577.516892317929), 565.40973075319, (-1577.516892317929), (-1577.516892317929));
      assertEquals((-1577.516892317929), conversorMoedas0.libra, 0.01);
      
      conversorMoedas0.setLibra(565.40973075319);
      double double0 = conversorMoedas0.getLibra();
      assertEquals(565.40973075319, conversorMoedas0.libra, 0.01);
      assertEquals(565.40973075319, double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      ConversorMoedas conversorMoedas0 = new ConversorMoedas((-1577.516892317929), 565.40973075319, (-1577.516892317929), (-1577.516892317929));
      double double0 = conversorMoedas0.getLibra();
      assertEquals((-1577.516892317929), conversorMoedas0.dolar, 0.01);
      assertEquals(565.40973075319, conversorMoedas0.euro, 0.01);
      assertEquals((-1577.516892317929), double0, 0.01);
      assertEquals((-1577.516892317929), conversorMoedas0.quantia, 0.01);
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      ConversorMoedas conversorMoedas0 = new ConversorMoedas(0.0, 0.0, 0.0, 0.0);
      double double0 = conversorMoedas0.getEuro();
      assertEquals(0.0, conversorMoedas0.quantia, 0.01);
      assertEquals(0.0, conversorMoedas0.dolar, 0.01);
      assertEquals(0.0, double0, 0.01);
      assertEquals(0.0, conversorMoedas0.libra, 0.01);
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      ConversorMoedas conversorMoedas0 = new ConversorMoedas(1.0, 1546.607325);
      double double0 = conversorMoedas0.getEuro();
      assertEquals(1546.607325, conversorMoedas0.quantia, 0.01);
      assertEquals(1.0, double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      ConversorMoedas conversorMoedas0 = new ConversorMoedas(0.0, 0.0);
      double double0 = conversorMoedas0.getDolar();
      assertEquals(0.0, double0, 0.01);
      assertEquals(0.0, conversorMoedas0.quantia, 0.01);
      assertEquals(0.0, conversorMoedas0.euro, 0.01);
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      ConversorMoedas conversorMoedas0 = new ConversorMoedas((-2189.3124944925), (-2189.3124944925), 723.903436224, 723.903436224);
      assertEquals((-2189.3124944925), conversorMoedas0.dolar, 0.01);
      
      conversorMoedas0.dolar = 723.903436224;
      double double0 = conversorMoedas0.getDolar();
      assertEquals(723.903436224, double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      ConversorMoedas conversorMoedas0 = new ConversorMoedas(0.0, 0.0);
      conversorMoedas0.libra = (-1203.258338354497);
      double double0 = conversorMoedas0.converteParaLibra(0.0);
      assertEquals(-0.0, double0, 0.01);
      assertEquals(0.0, conversorMoedas0.quantia, 0.01);
      assertEquals(0.0, conversorMoedas0.euro, 0.01);
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      ConversorMoedas conversorMoedas0 = new ConversorMoedas(0.0, 0.0);
      double double0 = conversorMoedas0.converteParaLibra(723.6810719723301);
      assertEquals(0.0, conversorMoedas0.quantia, 0.01);
      assertEquals(Double.POSITIVE_INFINITY, double0, 0.01);
      assertEquals(0.0, conversorMoedas0.euro, 0.01);
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      ConversorMoedas conversorMoedas0 = new ConversorMoedas((-743.9445903), 0.0, 0.0, 1742.6);
      double double0 = conversorMoedas0.converteParaLibra((-2734480.082125113));
      assertEquals(Double.NEGATIVE_INFINITY, double0, 0.01);
      assertEquals((-743.9445903), conversorMoedas0.dolar, 0.01);
      assertEquals(0.0, conversorMoedas0.euro, 0.01);
      assertEquals(1742.6, conversorMoedas0.quantia, 0.01);
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      ConversorMoedas conversorMoedas0 = new ConversorMoedas(1.0, 0.0);
      double double0 = conversorMoedas0.converteParaEuro(604.0);
      assertEquals(0.0, conversorMoedas0.quantia, 0.01);
      assertEquals(604.0, double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      ConversorMoedas conversorMoedas0 = new ConversorMoedas((-1.0), 0.0, 0.0, 0.0);
      double double0 = conversorMoedas0.converteParaEuro((-1.0));
      assertEquals(0.0, conversorMoedas0.libra, 0.01);
      assertEquals((-1.0), conversorMoedas0.dolar, 0.01);
      assertEquals(Double.NEGATIVE_INFINITY, double0, 0.01);
      assertEquals(0.0, conversorMoedas0.quantia, 0.01);
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      ConversorMoedas conversorMoedas0 = new ConversorMoedas(1.0, 1546.607325);
      conversorMoedas0.dolar = 1546.607325;
      double double0 = conversorMoedas0.converteParaDolar(0.0);
      assertEquals(1.0, conversorMoedas0.euro, 0.01);
      assertEquals(0.0, double0, 0.01);
      assertEquals(1546.607325, conversorMoedas0.quantia, 0.01);
  }

  @Test(timeout = 4000)
  public void test16()  throws Throwable  {
      ConversorMoedas conversorMoedas0 = new ConversorMoedas(1.0, 1.0);
      double double0 = conversorMoedas0.converteParaDolar(1.0);
      assertEquals(1.0, conversorMoedas0.euro, 0.01);
      assertEquals(1.0, conversorMoedas0.quantia, 0.01);
      assertEquals(Double.POSITIVE_INFINITY, double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test17()  throws Throwable  {
      ConversorMoedas conversorMoedas0 = new ConversorMoedas(0.0, 0.0);
      conversorMoedas0.setLibra(1.0);
      double double0 = conversorMoedas0.converteDeLibraParaReal(1.0);
      assertEquals(1.0, conversorMoedas0.libra, 0.01);
      assertEquals(1.0, double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test18()  throws Throwable  {
      ConversorMoedas conversorMoedas0 = new ConversorMoedas(0.0, 0.0, 1.0, 1.0);
      double double0 = conversorMoedas0.converteDeLibraParaReal((-1678.611));
      assertEquals(0.0, conversorMoedas0.euro, 0.01);
      assertEquals(0.0, conversorMoedas0.dolar, 0.01);
      assertEquals(1.0, conversorMoedas0.quantia, 0.01);
      assertEquals((-1678.611), double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test19()  throws Throwable  {
      ConversorMoedas conversorMoedas0 = new ConversorMoedas(0.0, 0.0);
      assertEquals(0.0, conversorMoedas0.euro, 0.01);
      
      conversorMoedas0.euro = 2115.503270873755;
      double double0 = conversorMoedas0.converteDeEuroParaReal(1659.1789898834);
      assertEquals(3509998.5800633454, double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test20()  throws Throwable  {
      ConversorMoedas conversorMoedas0 = new ConversorMoedas(2354.85277908, 2354.85277908);
      double double0 = conversorMoedas0.converteDeEuroParaReal((-1272.346483265748));
      assertEquals(2354.85277908, conversorMoedas0.quantia, 0.01);
      assertEquals((-2996188.6520710113), double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test21()  throws Throwable  {
      ConversorMoedas conversorMoedas0 = new ConversorMoedas(1.0, (-343.14484869));
      double double0 = conversorMoedas0.converteDeDolarParaReal((-343.14484869));
      assertEquals(1.0, conversorMoedas0.euro, 0.01);
      assertEquals(-0.0, double0, 0.01);
      assertEquals((-343.14484869), conversorMoedas0.quantia, 0.01);
  }

  @Test(timeout = 4000)
  public void test22()  throws Throwable  {
      ConversorMoedas conversorMoedas0 = new ConversorMoedas((-743.9445903), 0.0, 0.0, 1742.6);
      double double0 = conversorMoedas0.converteDeDolarParaReal(3675.6502);
      assertEquals(1742.6, conversorMoedas0.quantia, 0.01);
      assertEquals(0.0, conversorMoedas0.libra, 0.01);
      assertEquals(0.0, conversorMoedas0.euro, 0.01);
      assertEquals((-2734480.082125113), double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test23()  throws Throwable  {
      ConversorMoedas conversorMoedas0 = new ConversorMoedas(1.0, 1546.607325);
      conversorMoedas0.setDolar((-1413.052855));
      assertEquals((-1413.052855), conversorMoedas0.dolar, 0.01);
  }

  @Test(timeout = 4000)
  public void test24()  throws Throwable  {
      ConversorMoedas conversorMoedas0 = new ConversorMoedas(1.0, 1546.607325);
      double double0 = conversorMoedas0.converteParaEuro(0.0);
      assertEquals(1546.607325, conversorMoedas0.quantia, 0.01);
      assertEquals(0.0, double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test25()  throws Throwable  {
      ConversorMoedas conversorMoedas0 = new ConversorMoedas((-2189.3124944925), (-2189.3124944925), 723.903436224, 723.903436224);
      double double0 = conversorMoedas0.getDolar();
      assertEquals((-2189.3124944925), conversorMoedas0.euro, 0.01);
      assertEquals((-2189.3124944925), double0, 0.01);
      assertEquals(723.903436224, conversorMoedas0.quantia, 0.01);
      assertEquals(723.903436224, conversorMoedas0.libra, 0.01);
  }

  @Test(timeout = 4000)
  public void test26()  throws Throwable  {
      ConversorMoedas conversorMoedas0 = new ConversorMoedas(1.0, 1546.607325);
      double double0 = conversorMoedas0.converteDeLibraParaReal(1.0);
      assertEquals(1546.607325, conversorMoedas0.quantia, 0.01);
      assertEquals(1.0, conversorMoedas0.euro, 0.01);
      assertEquals(0.0, double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test27()  throws Throwable  {
      ConversorMoedas conversorMoedas0 = new ConversorMoedas((-2189.3124944925), (-2189.3124944925), 723.903436224, 723.903436224);
      double double0 = conversorMoedas0.converteDeEuroParaReal(0.0);
      assertEquals((-2189.3124944925), conversorMoedas0.dolar, 0.01);
      assertEquals(723.903436224, conversorMoedas0.quantia, 0.01);
      assertEquals(723.903436224, conversorMoedas0.libra, 0.01);
      assertEquals(-0.0, double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test28()  throws Throwable  {
      ConversorMoedas conversorMoedas0 = new ConversorMoedas((-2189.3124944925), (-2189.3124944925), 723.903436224, 723.903436224);
      double double0 = conversorMoedas0.somaValoresConverteDolar((-1492.0), 723.903436224);
      assertEquals((-768.096563776), conversorMoedas0.quantia, 0.01);
      assertEquals(1681603.404051552, double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test29()  throws Throwable  {
      ConversorMoedas conversorMoedas0 = new ConversorMoedas((-2189.3124944925), (-2189.3124944925), 723.903436224, 723.903436224);
      double double0 = conversorMoedas0.converteParaDolar(723.903436224);
      assertEquals(723.903436224, conversorMoedas0.quantia, 0.01);
      assertEquals(723.903436224, conversorMoedas0.libra, 0.01);
      assertEquals((-0.3306533160730015), double0, 0.01);
      assertEquals((-2189.3124944925), conversorMoedas0.euro, 0.01);
  }

  @Test(timeout = 4000)
  public void test30()  throws Throwable  {
      ConversorMoedas conversorMoedas0 = new ConversorMoedas(1.0, 1546.607325);
      double double0 = conversorMoedas0.getLibra();
      assertEquals(0.0, double0, 0.01);
      assertEquals(1.0, conversorMoedas0.euro, 0.01);
      assertEquals(1546.607325, conversorMoedas0.quantia, 0.01);
  }

  @Test(timeout = 4000)
  public void test31()  throws Throwable  {
      ConversorMoedas conversorMoedas0 = new ConversorMoedas((-475.145317), 0.0, 0.0, (-475.145317));
      conversorMoedas0.setEuro(435.40198826);
      assertEquals(435.40198826, conversorMoedas0.euro, 0.01);
  }

  @Test(timeout = 4000)
  public void test32()  throws Throwable  {
      ConversorMoedas conversorMoedas0 = new ConversorMoedas((-2189.3124944925), (-2189.3124944925), 723.903436224, 723.903436224);
      double double0 = conversorMoedas0.getQuantia();
      assertEquals(723.903436224, double0, 0.01);
      assertEquals(723.903436224, conversorMoedas0.libra, 0.01);
      assertEquals((-2189.3124944925), conversorMoedas0.dolar, 0.01);
      assertEquals((-2189.3124944925), conversorMoedas0.euro, 0.01);
  }

  @Test(timeout = 4000)
  public void test33()  throws Throwable  {
      ConversorMoedas conversorMoedas0 = new ConversorMoedas((-2189.3124944925), (-2189.3124944925), 723.903436224, 723.903436224);
      double double0 = conversorMoedas0.getEuro();
      assertEquals((-2189.3124944925), conversorMoedas0.dolar, 0.01);
      assertEquals((-2189.3124944925), double0, 0.01);
      assertEquals(723.903436224, conversorMoedas0.quantia, 0.01);
      assertEquals(723.903436224, conversorMoedas0.libra, 0.01);
  }

  @Test(timeout = 4000)
  public void test34()  throws Throwable  {
      ConversorMoedas conversorMoedas0 = new ConversorMoedas((-2189.3124944925), (-2189.3124944925), 723.903436224, 723.903436224);
      double double0 = conversorMoedas0.converteDeDolarParaReal((-3282.584888679));
      assertEquals(7186604.111017206, double0, 0.01);
      assertEquals((-2189.3124944925), conversorMoedas0.euro, 0.01);
      assertEquals(723.903436224, conversorMoedas0.libra, 0.01);
      assertEquals(723.903436224, conversorMoedas0.quantia, 0.01);
  }
}
